POST localhost:8080/person/updatePerson/31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQHlhaG9vLmNvbSIsIm5hbWUiOiJBZG1pbiIsImFnZSI6MjIsInBob25lIjoiKzcgOTAzIDMzMy00NC01NSIsInJvbGUiOiJBRE1JTiJ9.PhjYt5bIKrwGQpdr4FR5Oh-mT1NMJWS8QQhgi2LYRk4
Content-Type: application/json

{
  "name": "Update31",
  "age": "32",
  "email": "Update31@rambler.ru",
  "phoneNumber": "+7 950 156-72-85",
  "password": "password"
}


###